CREATE DATABASE MY_CATALOG


CREATE TABLE GENRE (
    ID SERIAL,
	NAME VARCHAR(50),
	PRIMARY KEY(ID)
	)

    CREATE TABLE LABEL (
    ID SERIAL,
	TITLE VARCHAR(50),
	COLOR VARCHAR(50),
	PRIMARY KEY(ID)
	)

    CREATE TABLE AUTHOR (
    ID SERIAL,
	FIRST_NAME VARCHAR(50),
	LAST_NAME VARCHAR(50),
	PRIMARY KEY(ID)
	)
CREATE TABLE SOURCE (
    ID SERIAL,
	NAME VARCHAR(50),
	PRIMARY KEY(ID)
	)



CREATE TABLE GAME (
ID SERIAL PRIMARY KEY,
	MULTIPLYAER VARCHAR(50),
	LAST_PLAYED_AT DATE,
	PUBLISHED_DATE DATE,
	ARCHIVED BOOLEAN,
	GENRE_ID INT,
	SOURCE_ID INT,
	AUTHOR_ID INT,
	LABEL_ID INT,
	CONSTRAINT FK_GENRE
	  FOREIGN KEY (GENRE_ID)
	       REFERENCES GENRE(ID),
	CONSTRAINT FK_AUTHOR
	  FOREIGN KEY (AUTHOR_ID)
	       REFERENCES AUTHOR(ID),
	CONSTRAINT FK_LABEL
	  FOREIGN KEY (LABEL_ID)
	       REFERENCES LABEL(ID),
	CONSTRAINT FK_SOURCE
	  FOREIGN KEY (SOURCE_ID)
	       REFERENCES SOURCE(ID)
)

CREATE TABLE BOOK (
ID SERIAL PRIMARY KEY,
	PUBLISHER VARCHAR(50),
	COVER_STATE VARCHAR(50),
	PUBLISHED_DATE DATE,
	ARCHIVED BOOLEAN,
	GENRE_ID INT,
	SOURCE_ID INT,
	AUTHOR_ID INT,
	LABEL_ID INT,
	CONSTRAINT FK_GENRE
	  FOREIGN KEY (GENRE_ID)
	       REFERENCES GENRE(ID),
	CONSTRAINT FK_AUTHOR
	  FOREIGN KEY (AUTHOR_ID)
	       REFERENCES AUTHOR(ID),
	CONSTRAINT FK_LABEL
	  FOREIGN KEY (LABEL_ID)
	       REFERENCES LABEL(ID),
	CONSTRAINT FK_SOURCE
	  FOREIGN KEY (SOURCE_ID)
	       REFERENCES SOURCE(ID)
)


CREATE TABLE MOVIE (
ID SERIAL PRIMARY KEY,
	SILENT VARCHAR(50),
	PUBLISHED_DATE DATE,
	ARCHIVED BOOLEAN,
	GENRE_ID INT,
	SOURCE_ID INT,
	AUTHOR_ID INT,
	LABEL_ID INT,
	CONSTRAINT FK_GENRE
	  FOREIGN KEY (GENRE_ID)
	       REFERENCES GENRE(ID),
	CONSTRAINT FK_AUTHOR
	  FOREIGN KEY (AUTHOR_ID)
	       REFERENCES AUTHOR(ID),
	CONSTRAINT FK_LABEL
	  FOREIGN KEY (LABEL_ID)
	       REFERENCES LABEL(ID),
	CONSTRAINT FK_SOURCE
	  FOREIGN KEY (SOURCE_ID)
	       REFERENCES SOURCE(ID)
)

CREATE TABLE MUSICALBUM (
ID SERIAL PRIMARY KEY,
	ON_SPOTIFY BOOLEAN,
	PUBLISHED_DATE DATE,
	ARCHIVED BOOLEAN,
	GENRE_ID INT,
	SOURCE_ID INT,
	AUTHOR_ID INT,
	LABEL_ID INT,
	CONSTRAINT FK_GENRE
	  FOREIGN KEY (GENRE_ID)
	       REFERENCES GENRE(ID),
	CONSTRAINT FK_AUTHOR
	  FOREIGN KEY (AUTHOR_ID)
	       REFERENCES AUTHOR(ID),
	CONSTRAINT FK_LABEL
	  FOREIGN KEY (LABEL_ID)
	       REFERENCES LABEL(ID),
	CONSTRAINT FK_SOURCE
	  FOREIGN KEY (SOURCE_ID)
	       REFERENCES SOURCE(ID)
)